### ISSUE TITLE
Search only within email

### ISSUE THREAD

**Issue by niklaas** [hendotcat/ppl#48]
First, great program! I love it. Second, could it be that only the email addresses are searched when I am querying the program through mutt? This is a bit enoying when people are using nicknames and I can't remember them -- and actually an address book should turn in and tell me the right email address. :-)

**Comment by the-reverend** [comment]
you can get a case insensitive search with `ppl grep -i username`

**Comment by hendotcat** [comment]
Wow oops, I've really let some old issues rot here. Gonna close this one as it looks like that workaround is okay!
