### ISSUE TITLE
Import vcard

### ISSUE THREAD

**Issue by ghost** [hendotcat/ppl#60]
Hi,

is there a way to import vcard example from owncloud?

Thanks

**Comment by untitaker** [comment]
Provided you have one contact per `vcf`-file, you can just copy them into the address book folder.

**Comment by beli3ver** [comment]
Where I can find the folder?

**Comment by untitaker** [comment]
It is the one you created with `ppl init`.

**Comment by michaelplews** [comment]
Unfortunately, this doesn't seem to work.

```
$ ~ cd ~/.contacts
$ ~ mv me.vcf meep.vcf
$ ~ ppl ls
me: Michael
```

No `meep` entry. I have confirmed that `~/.contacts` is my [address book] folder

**Comment by untitaker** [comment]
@michaelplews Presumably you have to commit the result as ppl uses git for indexing. That may have changed recently though.

**Comment by michaelplews** [comment]
Yep, you're exactly right. Added my new contact using:

```
$ ~ cd ~/.contacts
$ ~ cp me.vcf meep.vcf
$ ~ ppl ls
me: Michael
$ ~ git add .
$ ~ git commit
$ ~ ppl ls
me: Michael
meep: Michael
```

Thanks!

**Comment by hendotcat** [comment]
Ah almost exactly 4 years later I've just noticed this issue for the very first time! Glad to see it was resolved happily! 😄
