### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by ghost** [hendotcat/ppl#61]
When I try to install under Debian I get this message:

``` bash
malte@DeskUbu:~$ sudo gem install ppl
Building native extensions.  This could take a while...
ERROR:  Error installing ppl:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.2 -r ./siteconf20160229-4153-dkt9ec.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.2.0/gems/rugged-0.17.0.b6 for inspection.
Results logged to /var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/rugged-0.17.0.b6/gem_make.out
```

**Comment by untitaker** [comment]
You most likely need `ruby-dev`.

**Comment by beli3ver** [comment]
Thanks, that fixed it.

**Comment by the-reverend** [comment]
i had to `sudo apt-get install ruby-dev` to proceed as well.

**Comment by hendotcat** [comment]
Oh dear! I haven't used Linux in absolutely _years_ now so I'm a bit out of touch with some of these things. Glad to see the workaround got figured out at least. If anybody digs this up at some future date and it's still a problem, please feel free to send a pull request adding a note about it to the installation docs!
