### ISSUE TITLE
one vcard per contact?

### ISSUE THREAD

**Issue by eevvoor** [hendotcat/ppl#64]
I guess that I need to have one contact per vcard?
Tried to import my addressbook form radicale which stores by default all contacts in one vcard-file and could not use it in a sensible way with ppl
Would be nice to have a short note about this convention in the docs.

**Comment by acant** [comment]
@ycau Would it be helpful to have a command like:
```
ppl import filename.vcf
```
Which would try to bring in all the contacts in the file, and split them up, and check them in appropriately?

**Comment by hendotcat** [comment]
Yeah the one contact per vcard thing is really central to the design of ppl so it's not gonna budge easily. I like the `ppl import filename.vcf` idea very very much BTW and would totally merge a PR that added that if anyone sees this and wants to build it!
