### ISSUE TITLE
Bash completion needs to escape shell tokens

### ISSUE THREAD

**Issue by lkraav** [hendotcat/ppl#66]
When scraping a "First Last (Company)" name, `name` is set to `first_last_(company)`

This spells trouble for tab-completing
```
$ [-] ppl show first_last_(company) 
bash: syntax error near unexpected token `('
```

**Comment by hendotcat** [comment]
Is this the mutt scraping thing? Could be nice if that command would strip out anything except `[a-z0-9_]` I guess yeah! If anyone wants to go ahead and fix this in a PR then go for it!
