### ISSUE TITLE
Convert to use the vcard gem

### ISSUE THREAD

**Issue by acant** [hendotcat/ppl#68]
The [vcard](https://rubygems.org/gems/vcard) code has been extracted from vpim, and can probably be used instead. There are a variety of benefits:
* adds support for the UID field
* I think that it might address handling the unknown fields PR #58, but that does need to be confirmed

(This issue was originally discussed in #67 )

**Comment by hendotcat** [comment]
Totally agree that this would be a good change! If someone wants to give this a try in a PR it's probably a fairly doable change!

**Comment by acant** [comment]
Wow I opened this in 2017. :) I have not made time to work on it, but I have still be using ppl. :+1: 
I will re-open these issues if I can make some time to work on this.

@hendotcat as always, thank you for your work on this project. :tada:

**Comment by hendotcat** [comment]
Will keep on keeping the lights on until either I or someone else finds the time, motivation & inspiration to add some more magic to this thing @acant, no worries! If you find yourself having big ideas like huge backwards-incompatible changes, rewriting in a better language, or just wanna break a bunch of the tests to get something working, then as far as I'm concerned all options are on the table. If someone really wants to make this their own I'm even happy to pass the torch and stick a link in the top of the readme saying "hey, there's a newer better ppl over here ➡️". In the meantime I'm also happy keeping it on low power mode like this! Does seem to have a good core set of functionality to satisfy the main use case decently without a tonne of maintenance work!
