### ISSUE TITLE
Add support for the KIND field

### ISSUE THREAD

**Issue by acant** [hendotcat/ppl#69]
The [KIND](https://tools.ietf.org/html/rfc6350#section-6.1.4) allows a contact to be a individual, group or organization.

The conversion to the vcard gem should be done first, #68, then support for this field can be added to vcard and ppl.

(This issue was originally discussed in #67 )

**Comment by hendotcat** [comment]
This would kick ass! Since nobody's come along and built it so far in the past 4 years I'm gonna close this now under the assumption that the demand isn't there for it. But it sounds like an obvious and unambiguous win to me and I'd totally welcome a PR if circumstances change!
