### ISSUE TITLE
Add support for the NOTE field

### ISSUE THREAD

**Issue by acant** [hendotcat/ppl#71]
The vcard [NOTE](https://tools.ietf.org/html/rfc6350#section-6.7.2) field will allow an arbitrary chunk of text to be attached to a vcard. In the CLI, this should make use of the EDITOR environment variable to pick a text editor.

The conversion to the vcard gem should be done first, #68, then support for this field can be added to vcard and ppl.

(This issue was originally discussed in #67 )

**Comment by hendotcat** [comment]
Oof I have wanted this one so often. Such a handy field and one I actually use often in other address book apps. Kind of surprised I didn't already build it TBH. I'm probably not gonna get around to building it myself either, but would love it if someone else did and sent a pull request!
