### ISSUE TITLE
Add more code quality tools and their badges

### ISSUE THREAD

**Issue by acant** [hendotcat/ppl#73]
* TravisCI is already present, but something is wrong with the badge
* add the CodeClimate test coverage tool
* add rubocop, for local code quality checking
* add gemnasium, for dependency checking
* add inchci, for documentation checking
* add bundler-audit, for local security issue checking

(This issue was originally discussed in #67 )

**Comment by untitaker** [comment]
Also bundle audit if not already included

**Comment by acant** [comment]
Yes, I added bundle-audit to the description! Thanks @untitaker

**Comment by hnrysmth** [comment]
Yo sorry, I seem to very rarely check my Github notifications and it makes me a bit of a crap maintainer. Hang on, I'm gonna do a thing, check it out...

![enabel](https://user-images.githubusercontent.com/566159/29924577-a9b6334c-8e5d-11e7-9077-296e7f8566b1.gif)

Also @acant I've sent you an organization invite so you aren't stuck waiting for me if you wanna just do some of this stuff. Hit me up if you get to a point where you need publish access on the gem itself!

**Comment by acant** [comment]
thanks @hnrysmth

**Comment by hendotcat** [comment]
I hooked up GitHub's own dependabot stuff here a while back which has been really great. I think the only CI tool left on ppl these days is the GitHub deploy action. As time's gone by I've slimmed down those external dependencies as they tended to spam my inbox with nonsense errors and/or upsell from time to time.
