### ISSUE TITLE
autocomplete fails when it encounters invalid dates in the data set

### ISSUE THREAD

**Issue by the-reverend** [hendotcat/ppl#75]
i have some vcards with dates like `BDAY:19990500` - because i only know the month, e.g.:

```
BEGIN:VCARD
VERSION:3.0
BDAY:20000900
N:Wilstone;Matthew;;;
FN:Matthew Wilstone
NICKNAME:
END:VCARD
```

i also have some with year 0000 - because i don't know what year they were born, but ppl seems to be ok with that. anyway, autocomplete breaks because of this. type `ppl nick ang[TAB]` and i get this:

```
$ ppl nick angppl: invalid date
```

i'm sure it's because the vcard parser is intolerant of invalid dates and maybe there is no way around it and admittedly, i've created my own problem. however, it is surprising to me that autocomplete would invoke a full ppl card parse of the files just to autocomplete a filename match.

**Comment by the-reverend** [comment]
list also fails.
```
$ ppl ls
ppl: invalid date
```

**Comment by hendotcat** [comment]
Hahaha this sounds annoying! I have a lot of sympathy for the "only knowing the month" use-case that's driving this idea as well :joy: Probably not fixable though I'm afraid: you guessed exactly right and it's an upstream dependency.
