### ISSUE TITLE
Colorized and aligned custom address book format

### ISSUE THREAD

**Issue by fabrepe** [hendotcat/ppl#77]
In this issue, I refer to the ls command. I'm not aware if this would be applicable to some other commands.

Default formatting is clean: man can simply configure colors and output is aligned (using table class).
The ability to modify the output format is also a powerfull feature.
However, custom formats does not follow neither the configured ls colorscheme, nor the dynamic alignment, even if '%-\d*.' allows padding.

* Would it be possible to simply implement such custom formating ? I have never wrote ruby code.

 * From a specification point of view, what is the best solution to specify that custom format follows table formating instead of the current scanf format. For example, when parsing the configuration, if format string begins with '%t' it would be formatted and aligned like a table ?

**Comment by hendotcat** [comment]
You can probably put your own color code escapes in your custom format strings actually! If anyone swings by this issue searching for a workaround for this problem then that's probably your best bet!

https://tldp.org/pub/Linux/docs/ldp-archived/linuxfocus/English/Archives/lf-2004_05-0335.pdf
